version: 2.1

orbs:
  docker: circleci/docker@2.2

jobs:
  build:
    docker:
      - image: cimg/php:8.3
        environment:
          APP_ENV: testing
          DB_CONNECTION: sqlite
    steps:
      - checkout
      - restore_cache:
          keys:
            - composer-v1-{{ checksum "composer.lock" }}
      - run:
          name: Install dependencies
          command: composer install --no-interaction --prefer-dist --no-scripts
      - save_cache:
          paths:
            - vendor
          key: composer-v1-{{ checksum "composer.lock" }}
      - run:
          name: Generate app key for testing
          command: php artisan key:generate --env=testing
      - run:
          name: Prepare testing database
          command: |
            php artisan migrate --env=testing --force
      - run:
          name: Run tests
          command: php artisan test --env=testing
  docker-build-push-dev:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Login to dockerhub
          command: |
            echo "$DOCKER_PASS" | docker login --username $DOCKER_USER --password-stdin
      - run:
          name: Build dockerfile
          command: |
            docker build --no-cache -t rndmitraptek/tambak-udang:$CIRCLE_SHA1 .
      - run:
          name: Push Docker Image
          command: |
            docker push rndmitraptek/tambak-udang:$CIRCLE_SHA1
            docker tag rndmitraptek/tambak-udang:$CIRCLE_SHA1 rndmitraptek/tambak-udang:development-latest
            docker push rndmitraptek/tambak-udang:development-latest

workflows:
  build_and_push_dev:
    jobs:
      - build
      - docker-build-push-dev:
          requires:
            - build
          filters:
            branches:
              only: development   # <-- hanya jalan kalau branch development
